name: Generate Datas

on:
  schedule: # execute every 5 hours
    - cron: "0 */5 * * *" # Corrigido para agendar a cada 5 horas
  workflow_dispatch: # Permite a execução manual a partir da lista de Actions

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checa o código do repositório
      - uses: actions/checkout@v2

      # Gera o arquivo SVG da animação
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: gut0ddy
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Atualiza o GitHub Pages com os arquivos gerados
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
